theme = "catppuccin_mocha"

[editor]
# Visual enhancements
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true
true-color = true
auto-pairs = true

# Better cursor shapes
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Indentation guides
[editor.indent-guides]
render = true
character = "╎"

# Status line with git info
[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding"]

# LSP configuration
[editor.lsp]
display-messages = true
auto-signature-help = false

# File picker configuration
[editor.file-picker]
hidden = false
git-ignore = true
git-global = true

# Soft wrap
[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "↪ "

# Search configuration
[editor.search]
smart-case = true
wrap-around = true

# Whitespace rendering
[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

# Normal mode keybindings
[keys.normal]
# Quick config access
"C-o" = ":config-open"
"C-r" = ":config-reload"

# Better navigation (Helix style with vim muscle memory)
"C-h" = "select_prev_sibling"
"C-j" = "shrink_selection"
"C-k" = "expand_selection"
"C-l" = "select_next_sibling"

# Vim-like line operations
"o" = ["open_below", "insert_mode"]
"O" = ["open_above", "insert_mode"]

# Classic vim movements
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"G" = "goto_file_end"
"%" = "match_brackets"
"V" = ["select_mode", "extend_to_line_bounds"]

# Enhanced line operations
"C" = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
"D" = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
"S" = "surround_add"

# Better clipboard operations
"x" = "delete_selection"
"p" = ["paste_clipboard_after", "collapse_selection"]
"P" = ["paste_clipboard_before", "collapse_selection"]
"Y" = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]

# Vim-like word movements
"w" = ["move_next_word_start", "move_char_right", "collapse_selection"]
"W" = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
"e" = ["move_next_word_end", "collapse_selection"]
"E" = ["move_next_long_word_end", "collapse_selection"]
"b" = ["move_prev_word_start", "collapse_selection"]
"B" = ["move_prev_long_word_start", "collapse_selection"]

# Insert mode improvements
"i" = ["insert_mode", "collapse_selection"]
"a" = ["append_mode", "collapse_selection"]

# Better undo
"u" = ["undo", "collapse_selection"]

# Escape improvements
"esc" = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# Better j/k for soft wrap
"j" = "move_line_down"
"k" = "move_line_up"

# Buffer navigation
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"

# Vim-like delete operations
[keys.normal.d]
"d" = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
"t" = ["extend_till_char"]
"s" = ["surround_delete"]
"i" = ["select_textobject_inner"]
"a" = ["select_textobject_around"]
"j" = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
"k" = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
"w" = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
"G" = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]

# Vim-like yank operations
[keys.normal.y]
"y" = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
"j" = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
"k" = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
"w" = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
"G" = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]

# File operations with space leader
[keys.normal.space]
"w" = ":write"
"q" = ":quit"
"x" = ":write-quit"
"/" = "global_search"
"?" = "command_palette"

[keys.normal.space.f]
"f" = "file_picker"
"r" = "file_picker_in_current_directory"
"g" = "global_search"
"d" = ":sh yazi"

"b" = "buffer_picker"

# Insert mode keybindings
[keys.insert]
"esc" = ["collapse_selection", "normal_mode"]
"C-c" = ["collapse_selection", "normal_mode"]

# Select mode keybindings
[keys.select]
# Vim-like movements in select mode
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"G" = "goto_file_end"
"%" = "match_brackets"

# Operations in select mode
"D" = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
"C" = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"S" = "surround_add"
"u" = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
"U" = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Text objects
"i" = "select_textobject_inner"
"a" = "select_textobject_around"

# Insert/append in select mode
"tab" = ["insert_mode", "collapse_selection"]
"C-a" = ["append_mode", "collapse_selection"]

# Line selection
"k" = ["extend_line_up", "extend_to_line_bounds"]
"j" = ["extend_line_down", "extend_to_line_bounds"]

# Clipboard operations
"d" = ["yank_main_selection_to_clipboard", "delete_selection"]
"x" = ["yank_main_selection_to_clipboard", "delete_selection"]
"y" = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
"Y" = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
"p" = "replace_selections_with_clipboard"
"P" = "paste_clipboard_before"

# Escape
"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
